// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Artwork → Artwork*
 */
export interface ArtworkDocumentDataArtworkItem {
  /**
   * Artwork image field in *Artwork → Artwork*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artwork.artwork[].artwork_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  artwork_image: prismic.ImageField<never>;

  /**
   * Artwork title field in *Artwork → Artwork*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artwork.artwork[].artwork_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artwork_title: prismic.KeyTextField;

  /**
   * Artwork description field in *Artwork → Artwork*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artwork.artwork[].artwork_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artwork_description: prismic.KeyTextField;

  /**
   * Available field in *Artwork → Artwork*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: artwork.artwork[].available
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  available: prismic.BooleanField;

  /**
   * Featured field in *Artwork → Artwork*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: artwork.artwork[].featured
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Content for Artwork documents
 */
interface ArtworkDocumentData {
  /**
   * Artwork field in *Artwork*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: artwork.artwork[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  artwork: prismic.GroupField<Simplify<ArtworkDocumentDataArtworkItem>>;
}

/**
 * Artwork document from Prismic
 *
 * - **API ID**: `artwork`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtworkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArtworkDocumentData>,
    'artwork',
    Lang
  >;

/**
 * Item in *Exhibition → Exhibitions*
 */
export interface ExhibitionDocumentDataExhibitionsItem {
  /**
   * Exhibition image field in *Exhibition → Exhibitions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition.exhibitions[].exhibition_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  exhibition_image: prismic.ImageField<never>;

  /**
   * Exhibition title field in *Exhibition → Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition.exhibitions[].exhibition_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  exhibition_title: prismic.KeyTextField;

  /**
   * Exhibition description field in *Exhibition → Exhibitions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition.exhibitions[].exhibition_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  exhibition_description: prismic.RichTextField;

  /**
   * Exhibition date field in *Exhibition → Exhibitions*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition.exhibitions[].exhibition_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  exhibition_date: prismic.DateField;
}

/**
 * Content for Exhibition documents
 */
interface ExhibitionDocumentData {
  /**
   * Exhibitions field in *Exhibition*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition.exhibitions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  exhibitions: prismic.GroupField<
    Simplify<ExhibitionDocumentDataExhibitionsItem>
  >;
}

/**
 * Exhibition document from Prismic
 *
 * - **API ID**: `exhibition`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ExhibitionDocumentData>,
    'exhibition',
    Lang
  >;

export type AllDocumentTypes = ArtworkDocument | ExhibitionDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArtworkDocument,
      ArtworkDocumentData,
      ArtworkDocumentDataArtworkItem,
      ExhibitionDocument,
      ExhibitionDocumentData,
      ExhibitionDocumentDataExhibitionsItem,
      AllDocumentTypes,
    };
  }
}
